modified_gem_list/spree-import-products-master/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :product_imports, only: [:index, :new, :create, :image_upload]
    get "/product_import_details", to: "product_imports#import_details"
    get "/aok", to: "product_imports#aok"
    get "/image_import", to: "product_imports#image_import"
  end
end

modified_gem_list/spree-import-products-master/app/models/product_import.rb
class ProductImport < ApplicationRecord
end

modified_gem_list/spree-import-products-master/app/models/spree/product_import.rb
module Spree
  class ProductImport < ActiveRecord::Base
    has_one_attached :data_file
    belongs_to :user, class_name: Spree.user_class.to_s
    enum status: %i[pending success failed]

    validate :correct_mine_type

    def correct_mine_type
      if data_file.attached? && !data_file.content_type.in?(%w(text/csv))
        errors.add(:data_file, 'must be a CSV file')
      end
    end
  end
end

modified_gem_list/spree-import-products-master/app/controllers/spree/admin/product_imports_controller.rb
module Spree
  module Admin
    class ProductImportsController < BaseController


      def aok
                          
      end


      def image_import

        Dir.glob("lagyi_image/*") do |img|

          image = MiniMagick::Image.open("#{Rails.root}/lagyi_image/#{File.basename(img)}")

          ActiveStorage::Blob.create(
            key: SecureRandom::base58,
            filename: File.basename(img),
            content_type: File.extname(img).gsub(".","image/"),
            metadata:{"identified"=>true, "width"=> image[:width], "height"=>image[:height], "analyzed"=>true},
            service_name: "local",
            byte_size: File.size(img),
            checksum: Digest::SHA256.hexdigest(img),
            created_at: Time.now.strftime("%Y-%d-%m %H:%M:%S %Z")
          )
        end
      end

      def index
        redirect_to :action => :new
      end

      def new
        @product_import = Spree::ProductImport.new
      end

      def create
        @product_import = ProductImport.new(product_import_params)
        @product_import.file_name = product_import_params[:data_file].original_filename
        @product_import.user_id = spree_current_user.id
        @product_import.save!

        CreateProductsFromCsvJob.perform_later(@product_import)

        redirect_to admin_product_import_details_path
      end

      def import_details
        @product_imports = Spree::ProductImport.all.order("created_at DESC")
      end

      private
        def product_import_params
          params.require(:product_import).permit(:data_file)
        end
    end
  end
end

modified_gem_list/spree-import-products-master/app/views/spree/admin/product_imports/aok.html.erb
<% Dir.glob('app/assets/images/lagyi_image/SW1001/*').map do |path| %>

    <%= File.basename(path) %>

<% end.reduce(&:+) %>

modified_gem_list/spree-import-products-master/app/views/spree/admin/product_imports/image_import.html.erb
<h2>Import Image Data</h2>

modified_gem_list/spree-import-products-master/app/views/spree/admin/product_imports/import_details.erb
<% if @product_imports.empty? %>
  <div class="alert alert-info no-objects-found">No Product Imports found.</div>
<% else %>
  <table>
    <thead>
      <th>File name</th>
      <th>Created at</th>
      <th>Imported by</th>
      <th>Status</th>
      <th>Errors</th>
    </thead>
    <tbody>
      <% @product_imports.each do |import| %>
        <tr>
          <td><%= import.file_name %></td>
          <td><%= import.created_at.strftime("%d/%m/%Y %H:%M") %></td>
          <td><%= import.user.email %></td>
          <td><%= import.status %></td>
          <td><%= import.import_errors %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<style>
  table, th, td {
    border: 1px solid black;
    padding: 8px;
  }
</style>

modified_gem_list/spree-import-products-master/app/views/spree/admin/product_imports/new.html.erb
<h2>Import Products from CSV</h2>

<%= form_for([:admin, @product_import], :method => :post, :html => { :multipart => true }) do |f| %>
   <fieldset>
   <%= f.field_container :data_file do %>
      <%= f.file_field :data_file, accept: 'text/csv' %>
   <% end %>
   </fieldset>

   <br />
   <div data-hook="buttons" class="form-actions">
      <%= button "Import", 'ok', 'submit', {class: 'btn-success'} %>
   </div>
<% end %>

<br>
<h2>Import Products Image Data</h2>
 <%= link_to "Import Image", admin_image_import_path, class: 'btn btn-dark btn-success' %>